# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category', verbose_name='Group')),
            ],
        ),
    ]
